travis:
  secure:
    BINSTAR_TOKEN: qBsmHtzTl4syxZ9fuvC+hua9rQxHD7Tte2q8ZcQPYuChECRyRLT92eQS2QGF9VsyI8Zmqt3XsLU5bbpoa2Zb4u7P0X+l4lRese6fjwVYxESQl3Twpojcj2sp3ac/om0VBlTvEAKU0vzLo+kkId0tugql4r03kvkhnlLj/R1J3AkFHdJIabjnep0BmFeCxvoQteJGjkYWcXvCKIKwJa4klfiezpoyZfwpKcX+D+dMs3H4WbA2PWAM1B7sVj9PQ5SScgzsJ+0sIGkf6XJ/ovwSOnAGBbgjLQGhUE0WbGlKPuB4pJ4F5oIXviRSDCeMSlVU8MjmjytKU25XuXwk/6RVstX0TarTDdlu6ghfxPKa/tua/1wXzGyWlYH546Mc9Z+0BPipejQG6JRO7bSozePk5K/U0ItlHflmwgshQhb+eDwiJ+rEWre/ag5PCW1re4MufnLnc4ua8TLPEsHF1lWleMA07Svg2OAUSF6Emr/yNPachDvh8KCNqpmoodzbxf5GQChk9ogmSKZgnkYUPiRRY4pwrfEdMrmtvIs+dE7dQfQbqyDGvz20X1p6ZeRulpwMGjWEGrQmdmSu35ovFsARuxsXcl5XeSfgwWPrsnXdffS8JkdkzdjCEV3h34iJMRiPyk0wGlmn99c4rr98/jpomDaBUIlX5z3SiNgOXahf/Bo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
